export const MAKE_NEW_MOVE = "MAKE_NEW_MOVE"
export const GENERATE_CANDIDATE_MOVES = "GENERATE_CANDIDATE_MOVES"

export const CLEAR_CANDIDATE_MOVES = "CLEAR_CANDIDATE_MOVES"

export const OPEN_PROMOTION = "OPEN_PROMOTION"
export const CLOSE_POPUP = "CLOSE_POPUP"
export const CAN_CASTLE = "CAN_CASTLE"

export const STALEMATE = "STALEMATE"

export const NEW_GAME = "NEW_GAME"
